[meta]
name     = "Color Tables Customizer"
author   = "XertroV"
category = "Utilities"
version  = "0.2.0"

[script]
#__DEFINES__
# dependencies = ["MLHook", "MLFeedRaceData"]
optional_dependencies = ["Editor"]
